# ML_Models/configs/catboost_config.yaml   --> Like a recipe card, can change ingredients without rebuil kitchen
experiment_name: "CatBoost_Experiment"
random_state: 42
val_size: 0.2
cv_folds: 3
track_path: "logs/catboost_log.json"
save_path: "models/catboost_model.pkl"

data:
  file_path: "data/Jobs Data.xlsx"
  file_type: "excel"
  columns_needed:
    - "Job_Number"
    - "Job_Value"
    - "Total_Claimed"
    - "Total_Cost"
    - "Estimator"
    - "Foreman"
    - "Job_Area"
    - "Main_Contractor"
    - "Suburb"
    - "Supervisor"
    - "Job_Description"
    - "Saving_or_Loss"

    # Columns required for prediction (excludes target)
  feature_columns:
    - "Job_Number"
    - "Job_Value"
    - "Total_Claimed"
    - "Total_Cost"
    - "Estimator"
    - "Foreman"
    - "Job_Area"
    - "Main_Contractor"
    - "Suburb"
    - "Supervisor"
    - "Job_Description"

  target_column: "Saving_or_Loss"
  categorical_features:
    - "Estimator"
    - "Foreman"
    - "Job_Area"
    - "Main_Contractor"
    - "Suburb"
    - "Supervisor"
    - "Job_Description"

feature_engineering:
  operations:
    - name: "temp_profit"
      operation: "subtract"
      inputs: ["Total_Claimed", "Total_Cost"]
      output: "Temp_Profit"

  categorical_handling:
    fillna: "Unknown"
    encoding: "native"
    handle_missing: true # Add this

model:
  type: "catboost"
  task: "regression"
  params:
    loss_function: "RMSE"
    eval_metric: "RMSE"
    verbose: 0
  hyperparameter_search:
    enabled: true
    method: "randomized_search"
    n_iter: 5
    scoring: "neg_root_mean_squared_error"
    cv: 3
    param_distributions:
      depth: [5, 7, 9]
      learning_rate: [0.05, 0.1]
      iterations: [500, 1000]
